replicaCount: 2

image:
  repository: ghcr.io/OWNER/REPO   # se sobreescribe en el deploy con --set
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

# imagePullSecrets para GHCR privado (opcional en el lab con imagen pública)
imagePullSecrets: []
